config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("one_crm.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("leads/", include("one_crm.leads.urls", namespace="leads")),
    path("img2text/", include("one_crm.img2text.urls", namespace="img2text")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

one_crm/img2text/urls.py
# -*- encoding: utf-8 -*-
"""
@File    :   urls
@Time    :   2020/7/12 8:13 下午
@Author  :   Fan Lingjie
@Version :   1.0
@Contact :   fanlingjie@laiye.com
"""
from django.urls import path

from .views import card_form_view

app_name = "img2text"

urlpatterns = [
    path("", card_form_view, name="card"),
]

one_crm/leads/urls.py
# -*- encoding: utf-8 -*-
"""
@File    :   urls.py
@Time    :   2020/7/11 7:50 下午
@Author  :   Fan Lingjie
@Version :   1.0
@Contact :   fanlingjie@laiye.com
"""
from django.urls import path

from .views import (  # isort:skip
    lead_create_view,
    lead_detail_view,
    lead_update_view,
    lead_delete_view,
    lead_list_view,
)

app_name = "leads"

urlpatterns = [
    path("add/", lead_create_view, name="lead-add"),
    path("<int:pk>/", lead_detail_view, name="lead-detail"),
    path("<int:pk>/update/", lead_update_view, name="lead-update"),
    path("<int:pk>/delete/", lead_delete_view, name="lead-delete"),
    path("", lead_list_view, name="lead-list"),
]

one_crm/users/urls.py
from django.urls import path

from one_crm.users.views import (  # isort:skip
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

one_crm/chatbot/models.py
# from django.db import models

# Create your models here.

one_crm/leads/models.py
from django.db import models
from django.urls import reverse

from django.db.models import (  # isort:skip
    CharField,
    EmailField,
    TextField,
    FileField,
    DateTimeField,
)


class Lead(models.Model):
    name = CharField("名字", max_length=255)
    title = CharField("职称", max_length=255, blank=True)
    contact = CharField("联系方式", max_length=255, blank=True)
    email = EmailField("邮箱", blank=True)
    description = TextField("描述", blank=True)
    attachment = FileField("附件", upload_to="upload", blank=True)
    create_time = DateTimeField("创建时间", auto_now_add=True)
    update_time = DateTimeField("上次更新时间", auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("leads:lead-detail", kwargs={"pk": self.pk})

one_crm/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for one-crm.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

one_crm/img2text/forms.py
# -*- encoding: utf-8 -*-
"""
@File    :   forms
@Time    :   2020/7/12 8:06 下午
@Author  :   Fan Lingjie
@Version :   1.0
@Contact :   fanlingjie@laiye.com
isort:skip_file
"""

import pytesseract
from PIL import Image
from django import forms
from django.apps import apps

from .helpers import extract_name, extract_phone, extract_email

Lead = apps.get_model("leads", "Lead")


class CardForm(forms.Form):
    img = forms.FileField(label="请选择名片")

    def parse_card(self):
        img = Image.open(self.cleaned_data["img"])
        s = pytesseract.image_to_string(img, lang="chi_sim")
        contact = extract_phone(s)
        email = extract_email(s)
        name = extract_name(s)
        lead = Lead(
            name=name,
            contact=contact,
            email=email,
            description=s,
            attachment=self.cleaned_data["img"],
        )
        lead.save()
        return lead.pk

one_crm/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

one_crm/chatbot/views.py
# from django.shortcuts import render
from .bot_helper import bot


async def get_bot_response(text):
    return bot.get_response(text)

one_crm/img2text/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView

from .forms import CardForm


class CardFormView(FormView):
    template_name = "img2text/card_form.html"
    form_class = CardForm

    def form_valid(self, form):
        self.pk = form.parse_card()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy("leads:lead-update", kwargs={"pk": self.pk})


card_form_view = CardFormView.as_view()

one_crm/leads/views.py
from django.urls import reverse_lazy

from .models import Lead

from django.views.generic import (  # isort:skip
    ListView,
    DetailView,
    UpdateView,
    CreateView,
    DeleteView,
)


class LeadCreateView(CreateView):
    """
        新建视图
    """

    model = Lead
    fields = ["name", "title", "contact", "email", "description", "attachment"]


lead_create_view = LeadCreateView.as_view()


class LeadUpdateView(UpdateView):
    """
        更新视图
    """

    model = Lead
    fields = ["name", "title", "contact", "email", "description", "attachment"]


lead_update_view = LeadUpdateView.as_view()


class LeadDeleteView(DeleteView):
    """
        删除视图
    """

    model = Lead

    success_url = reverse_lazy("leads:lead-list")


lead_delete_view = LeadDeleteView.as_view()


class LeadListView(ListView):
    """
        线索列表视图
    """

    model = Lead


lead_list_view = LeadListView.as_view()


class LeadDetailView(DetailView):
    """
        线索详情视图
    """

    model = Lead


lead_detail_view = LeadDetailView.as_view()

one_crm/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

one_crm/templates/leads/lead_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>是否删除线索  "{{ object }}"?</p>
    <input type="submit" value="确定">
</form>
{% endblock content %}

one_crm/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <p class="lead"> {{ object.name }}</p>
    <hr class="my-4">
    <p>职称: {{ object.title }}</p>
    <p>联系方式: {{ object.contact }}</p>
    <p>邮箱: {{ object.email }}</p>
    <p>描述: {{ object.description }}</p>
    <p>附件: <a href="{{ object.attachment.url }}" target="_blank">文件地址</a></p>
    <a class="btn btn-primary btn-lg" href="{% url 'leads:lead-delete' lead.pk %}" role="button">删除</a>
    <a class="btn btn-primary btn-lg" href="{% url 'leads:lead-list' %}" role="button" style="float:right">返回列表</a>
  </div>
{% endblock content %}

one_crm/templates/leads/lead_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST" enctype="multipart/form-data">

    <!-- Security token -->
    {% csrf_token %}

    <!-- Using the formset -->
    {{ form|crispy }}

    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
      </div>
    </div>
</form>
{% endblock content %}

one_crm/templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}
  <h5>线索列表</h5>
  <div class="text-right">
    <a href="{% url 'img2text:card' %}" class="btn btn-primary">名片导入</a>
    <a href="{% url 'leads:lead-add' %}" class="btn btn-primary">新建</a>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">名字</th>
        <th scope="col">职位</th>
        <th scope="col">联系方式</th>
        <th scope="col">邮箱</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
     {% for lead in object_list %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ lead.name }}</td>
        <td>{{ lead.title }}</td>
        <td>{{ lead.contact }}</td>
        <td>{{ lead.email }}</td>
        <td><a href="{% url 'leads:lead-detail' pk=lead.pk %}">详情</a></td>
        <td><a href="{% url 'leads:lead-update' pk=lead.pk %}">更新</a></td>
        <td><a href="{% url 'leads:lead-delete' pk=lead.pk %}">删除</a></td>
      </tr>
     {% endfor %}
    </tbody>
  </table>
{% endblock %}